/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../design_candidate.v:1" *)
module seq_detect_101(clk, rst, bit_in, match);
  (* src = "../design_candidate.v:13" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "../design_candidate.v:4" *)
  input bit_in;
  (* src = "../design_candidate.v:2" *)
  input clk;
  (* src = "../design_candidate.v:5" *)
  output match;
  reg match;
  (* src = "../design_candidate.v:3" *)
  input rst;
  (* onehot = 32'd1 *)
  (* unused_bits = "0" *)
  wire [2:0] state;
  assign _02_ = bit_in & ~(rst);
  assign _04_ = state[1] & bit_in;
  assign _00_ = _04_ & ~(rst);
  assign _03_ = bit_in | rst;
  assign _01_ = state[2] & ~(_03_);
  (* src = "../design_candidate.v:13" *)
  always @(posedge clk)
      match <= _00_;
  reg \state_reg[1] ;
  always @(posedge clk)
      \state_reg[1]  <= _01_;
  assign state[1] = \state_reg[1] ;
  reg \state_reg[2] ;
  always @(posedge clk)
      \state_reg[2]  <= _02_;
  assign state[2] = \state_reg[2] ;
endmodule
