/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../design_candidate.v:1" *)
module rising_edge_detector(clk, rst, sig_in, pulse);
  (* src = "../design_candidate.v:9" *)
  wire _0_;
  (* src = "../design_candidate.v:9" *)
  wire _1_;
  wire _2_;
  (* src = "../design_candidate.v:2" *)
  input clk;
  (* src = "../design_candidate.v:7" *)
  reg prev_sig;
  (* src = "../design_candidate.v:5" *)
  output pulse;
  reg pulse;
  (* src = "../design_candidate.v:3" *)
  input rst;
  (* src = "../design_candidate.v:4" *)
  input sig_in;
  assign _2_ = sig_in & ~(prev_sig);
  assign _1_ = _2_ & ~(rst);
  assign _0_ = sig_in & ~(rst);
  (* src = "../design_candidate.v:9" *)
  always @(posedge clk)
      prev_sig <= _0_;
  (* src = "../design_candidate.v:9" *)
  always @(posedge clk)
      pulse <= _1_;
endmodule
