/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../design_candidate.v:1" *)
module button_debouncer(clk, rst, noisy_btn, clean_btn);
  (* src = "../design_candidate.v:10" *)
  wire _00_;
  (* src = "../design_candidate.v:10" *)
  wire _01_;
  (* src = "../design_candidate.v:10" *)
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "../design_candidate.v:5" *)
  output clean_btn;
  reg clean_btn;
  (* src = "../design_candidate.v:2" *)
  input clk;
  (* src = "../design_candidate.v:7" *)
  reg last_sample;
  (* src = "../design_candidate.v:4" *)
  input noisy_btn;
  (* src = "../design_candidate.v:3" *)
  input rst;
  (* src = "../design_candidate.v:8" *)
  reg [1:0] stable_count;
  assign _03_ = stable_count[1] & ~(stable_count[0]);
  assign _04_ = _03_ ? last_sample : clean_btn;
  assign _00_ = _04_ & ~(rst);
  assign _05_ = ~(noisy_btn ^ last_sample);
  assign _06_ = stable_count[0] & ~(stable_count[1]);
  assign _02_[0] = ~((_06_ & _05_) | rst);
  assign _07_ = ~((stable_count[1] | stable_count[0]) & _05_);
  assign _02_[1] = ~(_07_ | rst);
  assign _08_ = ~(noisy_btn & last_sample);
  assign _09_ = last_sample | ~(noisy_btn);
  assign _01_ = ~((_09_ & _08_) | rst);
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      last_sample <= _01_;
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      stable_count[0] <= _02_[0];
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      stable_count[1] <= _02_[1];
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      clean_btn <= _00_;
endmodule
