/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../design_candidate.v:1" *)
module shift_register_4bit(clk, rst, load, shift_en, serial_in, data_in, data_out);
  (* src = "../design_candidate.v:10" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "../design_candidate.v:2" *)
  input clk;
  (* src = "../design_candidate.v:7" *)
  input [3:0] data_in;
  (* src = "../design_candidate.v:8" *)
  output [3:0] data_out;
  reg [3:0] data_out;
  (* src = "../design_candidate.v:4" *)
  input load;
  (* src = "../design_candidate.v:3" *)
  input rst;
  (* src = "../design_candidate.v:6" *)
  input serial_in;
  (* src = "../design_candidate.v:5" *)
  input shift_en;
  assign _01_ = shift_en ? serial_in : data_out[0];
  assign _02_ = load ? data_in[0] : _01_;
  assign _00_[0] = _02_ & ~(rst);
  assign _03_ = shift_en ? data_out[0] : data_out[1];
  assign _04_ = load ? data_in[1] : _03_;
  assign _00_[1] = _04_ & ~(rst);
  assign _05_ = shift_en ? data_out[1] : data_out[2];
  assign _06_ = load ? data_in[2] : _05_;
  assign _00_[2] = _06_ & ~(rst);
  assign _07_ = shift_en ? data_out[2] : data_out[3];
  assign _08_ = load ? data_in[3] : _07_;
  assign _00_[3] = _08_ & ~(rst);
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      data_out[0] <= _00_[0];
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      data_out[1] <= _00_[1];
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      data_out[2] <= _00_[2];
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      data_out[3] <= _00_[3];
endmodule
