/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../design_candidate.v:1" *)
module seq_detector_0011(clk, reset, data_in, detected);
  (* src = "../design_candidate.v:10" *)
  wire _00_;
  (* src = "../design_candidate.v:10" *)
  wire _01_;
  wire [2:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "../design_candidate.v:2" *)
  input clk;
  (* src = "../design_candidate.v:4" *)
  input data_in;
  (* src = "../design_candidate.v:8" *)
  reg detect_pending;
  (* src = "../design_candidate.v:5" *)
  output detected;
  reg detected;
  reg [2:0] history;
  (* src = "../design_candidate.v:3" *)
  input reset;
  assign _01_ = detect_pending & ~(reset);
  assign _03_ = ~(history[0] & data_in);
  assign _04_ = history[2] | history[1];
  assign _05_ = ~(_04_ | _03_);
  assign _00_ = _05_ & ~(reset);
  assign _02_[0] = data_in & ~(reset);
  assign _02_[1] = history[0] & ~(reset);
  assign _02_[2] = history[1] & ~(reset);
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      history[0] <= _02_[0];
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      history[1] <= _02_[1];
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      history[2] <= _02_[2];
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      detect_pending <= _00_;
  (* src = "../design_candidate.v:10" *)
  always @(posedge clk)
      detected <= _01_;
endmodule
